[관리자] 로그인후 비밀번호 변경 및 로그아웃 추가
kookmin-sw/capstone-2023-09 pull request #113
Opened 2023-04-21 11:34 UTC by suyunup

## What's Changed?
로그인시 확인메세지 추가
비밀번호 변경 페이지 기능 연결
로그아웃 레이아웃 추가
## Screenshots
![스크린샷, 2023-04-21 20-33-08](https://user-images.githubusercontent.com/55117730/233625801-55a0ff02-2e2a-4ae9-99e4-e0c314b36fba.png)

2023-04-21 12:39 UTC, iioo3356 requested changes

2023-04-21 12:39 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
> +          setTimeout(function () {
antd message의 onClose 등 메써드를 이용하면 메시지 노출이 끝나면 자동으로 이동시켜줄 수 있지 않을까용?

2023-04-21 12:39 UTC, iioo3356 commented on src/front-end/timepay-admin/src/pages/Login/LoginPage.tsx
> +          setTimeout(function () {
요것도 message 메써드를 잘 쓰면 좋을 것 같아용

2023-04-21 12:39 UTC, iioo3356 commented on src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
> +            setTimeout(function () {
메세지....잘 써봐용

2023-04-21 12:39 UTC, iioo3356 commented on src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
> +          if (result.data.success === true) {
요 비교문 없어도 항상 data의 success가 true일 때 호출될 것 같습니다

2023-04-22 12:33 UTC, seiyoon approved these changes
👌👌

2023-04-22 17:18 UTC, JinLee25154 approved these changes
GOOD 😊

2023-04-23 10:33 UTC, suyunup commented on src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
> +          if (result.data.success === true) {
수정했습니당

2023-04-23 10:41 UTC, iioo3356 approved these changes

2023-04-23 10:41 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
> +          setTokenToCookie(result.data.jwt, 0);
오 그냥 0으로만 넣어도 삭제 잘 되나용?
https://bluemint.tistory.com/6 처럼 쿠키 삭제하는 함수를 관리자, 사용자 화면에 만들어도 좋을 것 같아요!

2023-04-23 10:41 UTC, iioo3356 commented on src/front-end/timepay-admin/src/api/hooks/logout.ts
확인했습니당 감사합니다~

2023-04-23 10:41 UTC, iioo3356 commented on src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
> +          if (result.data.success === true) {
확인했습니다 감사합니당

2023-04-23 10:41 UTC, iioo3356 commented on src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
> +            setTimeout(function () {
확인했습니다 감사합니당

2023-04-23 10:41 UTC, iioo3356 commented on src/front-end/timepay-admin/src/pages/Login/LoginPage.tsx
> +          setTimeout(function () {
확인했습니다 감사합니당

2023-04-23 10:41 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
> +          setTimeout(function () {
확인했습니다 감사합니당

2023-04-23 10:42 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
> +        onSuccess: () => {
확인했습니다 감사합니당

2023-04-23 10:42 UTC, iioo3356 commented
고생하셨습니당! 😙

2023-04-23 10:43 UTC, suyunup commented on src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
> +          setTokenToCookie(result.data.jwt, 0);
넵 해볼게용

2023-04-23 11:37 UTC, merged