[design] 관리자 관리 화면 UI 개발
kookmin-sw/capstone-2023-09 pull request #47
Opened 2023-03-19 09:49 UTC by suyunup

## What's Changed? 
관리자 관리 화면
일반관리자 조회, 추가, 삭제 , 수정 UI

## Screenshots

![스크린샷, 2023-03-19 18-42-58](https://user-images.githubusercontent.com/55117730/226166830-c3d9fdc5-3a93-4072-b3f7-f4a6b0efc142.png)

2023-03-19 14:14 UTC, iioo3356 commented on src/front-end/timepay-admin/package-lock.json
통일성을 위해서 package 사용은 지양해주세요!
yarn 사용해서 add 해주시면 감사하겠습니다😘

2023-03-19 14:35 UTC, iioo3356 requested changes

2023-03-19 14:35 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/AdminMainTable/AdminAdd.tsx
> +/* eslint-disable no-template-curly-in-string */
요 주석들은 꼭 써야할 이유가 있을까요?

2023-03-19 14:35 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/AdminMainTable/AdminAdd.tsx
> +  ////////////////////////////////////////////////////
필요없는 주석(칸 나누기용, 코드로 잘 보이는 내용)은 지워주셔도 될 것 같습니다!

2023-03-19 14:35 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/AdminMainTable/AdminAdd.tsx
> +  const [modal2Open, setModal2Open] = useState(false);
isOpenAdminAddModal 등등 변수 이름을 좀 더 구체적으로 지어주시는게 가독성이 좋을 것 같습니다!

2023-03-19 14:35 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/AdminMainTable/AdminMainTable.tsx
> +const EditableCell: React.FC<EditableCellProps> = ({
EditableCell을 파일을 따로 분리해서 Import 해서 쓰는 것도 좋을 것 같습니다

2023-03-20 11:57 UTC, seiyoon approved these changes

2023-03-21 03:49 UTC, merged