[사용자] 게시글 작성 화면 개발
kookmin-sw/capstone-2023-09 pull request #48
Opened 2023-03-19 13:42 UTC by seiyoon

## What's Changed? 
❕자유/도움주기/도움받기 게시글 작성 화면 구현   
❕모든 내용(카테고리태그, 날짜, 시간, 장소) 입력 시에 버튼 활성화   
❕시간 선택에 따른 타임페이 환산 구현   
❗️recoil state 사용으로 태그, 타임페이가 지속된다는 문제 있음 (추후 수정할 예정)   
❗️antd 컴포넌트가 스크롤 될 때 header 부분 위로 지나간다는 에러 있음  

## Screenshots
대표로 도움받기 게시글 작성 화면 첨부합니다   
<img width="246" alt="스크린샷 2023-03-19 오후 9 56 15" src="https://user-images.githubusercontent.com/66265618/226178551-565e7df9-ecd5-4380-a2bc-028ca5618f56.png">

2023-03-19 14:13 UTC, iioo3356 commented on src/front-end/timepay-front/package-lock.json
통일성을 위해서 package 사용은 지양해주세요!
yarn 사용해서 add 해주시면 감사하겠습니다😘

2023-03-19 14:30 UTC, iioo3356 requested changes

2023-03-19 14:30 UTC, iioo3356 commented on src/front-end/timepay-front/src/styles/constants/customTheme.ts
> +    colorPrimary: '#FFC700',
나중에 사용하기 편하도록 COMMON_COLOR 파일에 해당 컬러 추가해주시면 좋을 것 같습니다!

2023-03-19 14:30 UTC, iioo3356 commented on src/front-end/timepay-front/src/pages/index.ts
문의 게시글 작성 화면은 어디로 이동하는 걸지 궁금합니다!

2023-03-19 14:30 UTC, iioo3356 commented on src/front-end/timepay-front/src/components/MainHeader/MainHeader.styles.tsx
> +  height: 60px;
다른 페이지에서도 함께 쓰고 있어서 이 부분은 다같이 확인을 하고 수정해야할 것 같습니다.

2023-03-19 14:30 UTC, iioo3356 commented on src/front-end/timepay-front/src/components/register/TimeSelect.tsx
> +      <Select
antd의 TimePicker를 이용하면 더 빨리 개발할 수 있을 것 같습니다!

2023-03-19 14:30 UTC, iioo3356 commented on src/front-end/timepay-front/src/App.tsx
> +          <Route>
베이스 레이아웃 라우터 안에 해당 페이지들을 넣고 베이스 레이아웃에서 해당 페이지들의 주소일 때 Footer를 적용하지 않도록 하면 더 좋을 것 같습니다!

2023-03-19 14:32 UTC, seiyoon commented on src/front-end/timepay-front/src/pages/index.ts
문의 게시글 작성 화면은 아직 안 올렸어요. 문의 화면에 포함되어 후에 올릴 예정입니다 :)

2023-03-19 14:33 UTC, seiyoon commented on src/front-end/timepay-front/src/components/register/TimeSelect.tsx
> +      <Select
TimePicker 사용이 오히려 사용자(주민들)이 사용하기 더 불편하다고 느껴 이렇게 개발했었습니다..ㅎㅎ (당근마켓 참고해서 만든 것도 있..습니당)

2023-03-19 14:34 UTC, seiyoon commented on src/front-end/timepay-front/src/styles/constants/customTheme.ts
> +    colorPrimary: '#FFC700',
네!! ☑️

2023-03-19 14:38 UTC, seiyoon commented on src/front-end/timepay-front/src/components/MainHeader/MainHeader.styles.tsx
> +  height: 60px;
그러네요 ㅠㅠ 다시 70px으로 수정하겠습니다!

2023-03-19 14:42 UTC, iioo3356 commented on src/front-end/timepay-front/src/pages/index.ts
넵 알겠습니다!! 😘

2023-03-19 14:44 UTC, iioo3356 commented on src/front-end/timepay-front/src/components/register/TimeSelect.tsx
> +      <Select
오 그렇군요! 확실히 주민들은 셀렉트가 더 편할 수도 있을 것 같아요!
그래도 하드코딩인 감이 있는데 for 문을 돌려서 옵션 값을 추가해보는 건 어떨까요?

2023-03-20 01:52 UTC, iioo3356 commented on src/front-end/timepay-front/package.json
> +    "moment": "^2.29.4",
dayjs가 아니라 moment를 사용한 이유가 있을까요?

2023-03-20 07:17 UTC, seiyoon commented on src/front-end/timepay-front/package.json
> +    "moment": "^2.29.4",
개발 중에 사용할까 싶어 설치했다가 사용을 안했네요..! 제거해서 다시 올렸어요~

2023-03-20 09:18 UTC, iioo3356 commented on src/front-end/timepay-front/src/components/register/TimeSelect.tsx
> +      <Select
수정해주신 거 확인했습니다! 감사합니당

2023-03-20 09:19 UTC, iioo3356 commented on src/front-end/timepay-front/src/styles/constants/customTheme.ts
> +    colorPrimary: '#FFC700',
확인했습니다! 감사합니당

2023-03-20 09:20 UTC, iioo3356 commented on src/front-end/timepay-front/src/components/MainHeader/MainHeader.styles.tsx
> +  height: 60px;
확인했습니다! 감사합니당

2023-03-20 09:24 UTC, iioo3356 requested changes

2023-03-20 09:24 UTC, iioo3356 commented on src/front-end/timepay-front/package-lock.json
요 파일도 지워서 올려주시면 감사하겠습니다!

2023-03-20 09:24 UTC, iioo3356 commented on src/front-end/timepay-front/src/App.tsx
> +          <Route>
혹시 요거 당장 하기 어려우시다면 제가 다음주 월요일 머지 때까지 고쳐봐도 될까요?

2023-03-20 11:09 UTC, iioo3356 commented on src/front-end/timepay-front/package-lock.json
확인했습니다! 감사합니당

2023-03-20 15:04 UTC, suyunup approved these changes

2023-03-21 00:50 UTC, seiyoon commented on src/front-end/timepay-front/src/pages/RegisterPage/RegisterServePage.tsx
> +  //
확인 부탁드려용

2023-03-21 04:18 UTC, closed without merging