[design]카테고리 관리 UI 추가
kookmin-sw/capstone-2023-09 pull request #50
Opened 2023-03-19 14:21 UTC by suyunup

## What's Changed? 
카테고리 관리 화면
카테고리 조회, 추가, 삭제, 수정 UI

## Screenshots

![스크린샷, 2023-03-19 23-19-37](https://user-images.githubusercontent.com/55117730/226182304-9eaf1294-879f-473c-964f-4cd326222b54.png)

2023-03-20 00:56 UTC, iioo3356 requested changes

2023-03-20 00:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryAdd.tsx
> +/* eslint-disable no-template-curly-in-string */
꼭 필요하지 않은 주석이라면 삭제 부탁드릴게요!

2023-03-20 00:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryAdd.tsx
> +  const [modal2Open, setModal2Open] = useState(false);
좀 더 구체적인 변수명을 사용하는 게 좋을 것 같습니다!

2023-03-20 00:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryAdd.tsx
> +      name="nest-messages"
이 nest-messages가 의미하는 게 어떤 걸지 궁금합니다!

2023-03-20 00:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryAdd.tsx
> +      </Form.Item>
Form.Item name에 있는 user는 꼭 필요한 값일까요?

2023-03-20 00:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryAdd.tsx
CategoryAdd.tsx와 CategoryAdd.styles.tsx는 폴더를 따로 빼거나 
CategoryTable 폴더의 이름을 좀 더 포괄적으로 작성해도 좋을 것 같습니다!

2023-03-20 00:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryTable.tsx
> +const EditableCell: React.FC<EditableCellProps> = ({
리턴문이 있어서 다른 파일에 작성하는 게 더 좋을 것 같습니다!

2023-03-20 00:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryTable.tsx
> +          <Popconfirm
영어 메시지보다는 한글로 전달하는 쪽이 좋을 것 같습니다!

2023-03-20 10:54 UTC, seiyoon approved these changes

2023-03-20 10:59 UTC, seiyoon reviewed
key: i+1로 해서 사용자에게 보일 카테고리 번호는 1부터 시작하는게 좋을 것 같다는 생각이 듭니다..ㅎㅎ 다른 건 좋아요! approve 했어요 :)

2023-03-20 10:59 UTC, seiyoon commented on src/front-end/timepay-admin/src/components/CategoryTable/CategoryTable.tsx
> +    key: i,
key: i+1로 해서 사용자에게 보일 카테고리 번호는 1부터 시작하는게 좋을 것 같다는 생각이 듭니다..ㅎㅎ 다른 건 좋아요! approve 했어요 :)

2023-03-21 03:56 UTC, JinLee25154 approved these changes

2023-03-21 04:18 UTC, closed without merging