firstProto (Frontend - 이진)
kookmin-sw/capstone-2023-09 pull request #51
Opened 2023-03-19 17:41 UTC by JinLee25154

## What's Changed? 
1. **Login Page**: 카카오 로그인 API 인가코드(Authorization) 발급 완료(나머지 부분은 백엔드 구현), 인가코드 서버 전송 테스트 완료
2. **Join Page**: 프로필 이미지 업로드 및 사용자 정보 입력폼 구현 완료 (이름, 닉네임, 지역, 핸드폰 번호, 소개)
3. **My Page**: 사용자 정보 배치 및 4개 페이지(문의, 즐겨찾기 등) 이동 구현 완료 (프로필 이미지, 닉네임, 고유번호, 타임페이, 지역, 소개)
4. **My Page Edit**: 사용자 정보 수정폼 구현 완료 (프로필 이미지, 이름, 닉네임, 소개 등)

## Screenshots
![화면 캡처 2023-03-20 022415](https://user-images.githubusercontent.com/54920331/226195808-9946f412-3a72-4160-94f9-868bd93ffdfa.png)

![화면 캡처 2023-03-20 022452](https://user-images.githubusercontent.com/54920331/226195824-4653ea2a-8df7-464c-985a-58fcb9de41e8.png)

![화면 캡처 2023-03-20 022555](https://user-images.githubusercontent.com/54920331/226195839-f62db81a-84ba-442f-8f0b-ba4d5f2e816c.png)

![화면 캡처 2023-03-20 022817](https://user-images.githubusercontent.com/54920331/226195843-a37070fb-20c7-4c0e-b71f-f5d93d0e4ebb.png)

![화면 캡처 2023-03-20 023004](https://user-images.githubusercontent.com/54920331/226195850-7a21f2bc-b768-456e-ab76-e8907039b057.png)

![화면 캡처 2023-03-20 023022](https://user-images.githubusercontent.com/54920331/226195854-0f8dd244-137b-495b-9b76-81217b1b9ae0.png)

2023-03-20 00:33 UTC, iioo3356 commented on src/front-end/timepay-front/client/.eslintrc
client 폴더를 따로 만드신 이유가 있을까요?? src 폴더 안에 개발한 내용이 들어가야할 것 같아서요!

2023-03-20 00:48 UTC, iioo3356 requested changes
emotion, ant design을 좀 더 활용해주시면 감사하겠습니다!

2023-03-20 00:48 UTC, iioo3356 commented on src/front-end/timepay-front/package.json
타임페이 사용자화면 프론트에서 공용으로 사용하는 파일이라 필요한 라이브러리만 추가해주시는 게 안전할 것 같습니다!
name이나 version 등은 바꾼 이유가 있을까요?

2023-03-20 00:48 UTC, iioo3356 commented on src/front-end/timepay-front/package-lock.json
통일성을 위해서 package 사용은 지양해주세요!
yarn 사용해서 add 해주시면 감사하겠습니다😘

2023-03-20 00:48 UTC, iioo3356 commented on src/front-end/timepay-front/client/src/pages/JoinPage/Join.css
emotion을 사용해서 css를 적용하는 것도 좋을 것 같습니다!

2023-03-20 00:48 UTC, iioo3356 commented on src/front-end/timepay-front/client/src/pages/JoinPage/JoinPage.tsx
> +      <div className="contentWrap">
antd의 Form, Input 등 컴포넌트를 사용하면 필수값 체크 등을 더 효율적으로 할 수 있을 것 같습니다!

2023-03-20 00:48 UTC, iioo3356 commented on src/front-end/timepay-front/client/src/pages/JoinPage/Join_imageSet.tsx
> +    if (imageFile !== null) {
이 부분 if (imageFile) 로도 충분히 체크될 것 같습니다!

2023-03-20 00:48 UTC, iioo3356 commented on src/front-end/timepay-front/client/src/pages/JoinPage/Join_imageSet.tsx
> +          <input
antd의 Upload 컴포넌트를 이용할 수도 있을 것 같아요!

2023-03-20 00:48 UTC, iioo3356 commented on src/front-end/timepay-front/client/src/pages/JoinPage/Join_selectTown.tsx
> +    <div className="selectWrap">
antd의 Form, Select를 활용할 수 있을 것 같습니다!

2023-03-20 01:04 UTC, iioo3356 commented
base repository를 kookmin-sw:master 가 아니라 kookmin-sw:develop으로 바꿔주세용!

2023-03-20 01:43 UTC, JinLee25154 commented on src/front-end/timepay-front/client/.eslintrc
1. 서버로 데이터 전송
2. 서버로부터 데이터 수신 및 응답 받기

백엔드 합치기 전 테스트를 위해 테스트 서버를 만들었습니다!

2023-03-20 01:47 UTC, iioo3356 commented on src/front-end/timepay-front/client/.eslintrc
넵 이해했습니다!
나중에 충분히 수정할 수 있는 부분으로 보이는데 client 폴더와 src 폴더에 형식이 동일하기 때문에 client 폴더의 파일들을 src에 추가해주셔도 될 것 같습니다!

2023-03-20 09:27 UTC, iioo3356 commented
> base repository를 kookmin-sw:master 가 아니라 kookmin-sw:develop으로 바꿔주세용!

2023-03-20 15:14 UTC, suyunup approved these changes

2023-03-21 00:46 UTC, seiyoon commented on src/front-end/timepay-front/client/src/pages/LoginPage/Login.css
emotion 사용해서 css파일 작성해주시면 좋을 것 같아요!

2023-03-21 04:18 UTC, closed without merging