[사용자] 문의 화면 개발
kookmin-sw/capstone-2023-09 pull request #70
Opened 2023-03-25 10:21 UTC by seiyoon

## What's Changed?
문의화면으로 문의목록화면, 문의상세화면, 문의작성화면으로 구성되어 있음

## Screenshots
<img width="499" alt="스크린샷 2023-03-25 오후 7 17 44" src="https://user-images.githubusercontent.com/66265618/227711293-db5c4133-eb61-47dc-8b1d-96a33c51f61e.png">   
<img width="499" alt="스크린샷 2023-03-25 오후 7 17 52" src="https://user-images.githubusercontent.com/66265618/227711302-44241992-d028-4ea5-a590-8d5ec5529532.png">   
<img width="499" alt="스크린샷 2023-03-25 오후 7 17 58" src="https://user-images.githubusercontent.com/66265618/227711307-0110c952-ac3d-4707-9fe2-9c42f4e27320.png">

2023-03-27 03:48 UTC, iioo3356 requested changes

2023-03-27 03:48 UTC, iioo3356 commented on src/front-end/timepay-front/src/pages/QnaPage/QnaListPage.tsx
> +          <QnaList key={qna ? qna.qnaId : index} qna={qna} />
index 값을 넣은 이유가 있을까요? 정상적인 경우면 항상 qna.Id가 들어갈 것 같아서요!

2023-03-27 03:48 UTC, iioo3356 commented on src/front-end/timepay-front/src/pages/QnaPage/QnaDetailPage.style.tsx
> +export const cssQnaDetail2Style = css`
그냥 cssQnaDetailStyle이랑 어떤 다른 점이 있는지를 변수명으로 설명해주면 더 좋을 것 같아요! 아래 cssLine2Style 도요~~!

2023-03-27 10:42 UTC, suyunup approved these changes
수고하셨습니다~~

2023-03-27 14:22 UTC, JinLee25154 approved these changes
수고하셨습니다 :)

2023-03-28 10:33 UTC, seiyoon commented on src/front-end/timepay-front/src/pages/QnaPage/QnaListPage.tsx
> +          <QnaList key={qna ? qna.qnaId : index} qna={qna} />
수정했습니다~ 확인 부탁해용

2023-03-28 10:34 UTC, seiyoon commented on src/front-end/timepay-front/src/pages/QnaPage/QnaDetailPage.style.tsx
> +export const cssQnaDetail2Style = css`
이거는 너무 많은 이름들이 이렇게 작성되어 있어서요.. 우선 이번에는 넘어가고 중간평가 이후에 수정해도 될까요..?ㅠㅠ

2023-03-28 14:34 UTC, iioo3356 commented on src/front-end/timepay-front/src/pages/QnaPage/QnaDetailPage.style.tsx
> +export const cssQnaDetail2Style = css`
넵넵 좋아요!! 고생하셨습니다~~!!

2023-03-29 05:27 UTC, merged