[사용자] 검색 화면 UI 개발
kookmin-sw/capstone-2023-09 pull request #71
Opened 2023-03-25 21:31 UTC by iioo3356

## What's Changed? 
검색화면 UI 개발.
새로운 검색헤더 추가.
검색 헤더 안에는 Collapse 컴포넌트를 사용해 제목 외 검색값 부분을 가림.

## Screenshots
![Screen Shot 2023-03-26 at 6 25 10 AM](https://user-images.githubusercontent.com/54922639/227742937-513d3f3b-134d-41a5-a946-063c260d2d23.png)
![Screen Shot 2023-03-26 at 6 25 19 AM](https://user-images.githubusercontent.com/54922639/227742940-6bf5c447-7a6e-4a48-83d2-6814a3841501.png)
![Screen Shot 2023-03-26 at 6 25 31 AM](https://user-images.githubusercontent.com/54922639/227742942-c96247dc-29e6-411c-9169-5e9f05af78af.png)
![Screen Shot 2023-03-26 at 6 26 02 AM](https://user-images.githubusercontent.com/54922639/227742945-5ac0da68-f7e2-49ae-a1a8-1b5776e92f4c.png)

2023-03-27 11:07 UTC, suyunup requested changes

2023-03-27 11:07 UTC, suyunup commented on src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
> +  border-bottom: 1px solid #cdcdcd;
색상 등록해서 사용하는게 좋을거 같아용 admin에서는 Light Gray로 등록했습니다 !

2023-03-27 11:07 UTC, suyunup commented on src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
> +  border-bottom: 1px solid #cdcdcd;
어라 사용자 컬러에 이미 light gray 있네요 ???  silver gray 정도로 하면 될거 같아요 ㅎㅎ

2023-03-27 11:15 UTC, iioo3356 commented on src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
> +  border-bottom: 1px solid #cdcdcd;
넵넵!!

2023-03-27 11:23 UTC, suyunup commented
수고하셨습니당 ㅎㅎ

2023-03-27 17:07 UTC, seiyoon approved these changes
🤩👍
+) 궁금한 게 하나 있습니다 ㅎㅎ 이거 SearchPage의 더미 데이터는 HomePage의 더미 데이터와 별도로 검색 UI 구현 위해 사용하신 건가요??

2023-03-28 01:02 UTC, iioo3356 commented
아뇽 홈화면에 있던 더미데이터를 그대로 복붙해서 썼습니다! 더미 데이터를 위한 파일을 따로 만드는 게 좋을까요? @seiyoon

2023-03-28 06:08 UTC, seiyoon commented
> 아뇽 홈화면에 있던 더미데이터를 그대로 복붙해서 썼습니다! 더미 데이터를 위한 파일을 따로 만드는 게 좋을까요? @seiyoon



> 아뇽 홈화면에 있던 더미데이터를 그대로 복붙해서 썼습니다! 더미 데이터를 위한 파일을 따로 만드는 게 좋을까요? @seiyoon

아니요! 이대로 해도 좋을 것 같아요! 궁금해서 물어봤었어요,,ㅎ

2023-03-28 06:12 UTC, iioo3356 commented
> 아니요! 이대로 해도 좋을 것 같아요! 궁금해서 물어봤었어요,,ㅎ

ㅎㅎ 넵넵 감사합니당!!

2023-03-28 06:12 UTC, merged