[관리자] 신고관리 화면 UI 추가
kookmin-sw/capstone-2023-09 pull request #76
Opened 2023-03-26 20:30 UTC by suyunup

## What's Changed?
신고관리 조회 화면
신고 사유/신고대상 내용 조회 모달
신고 처리/반려 UI
## Screenshots
![스크린샷, 2023-03-27 05-04-52](https://user-images.githubusercontent.com/55117730/227802476-f46564d8-6fb2-4a85-af51-2c2bb1ce2cc0.png)
![스크린샷, 2023-03-27 05-04-57](https://user-images.githubusercontent.com/55117730/227802477-3cce9dc2-40ed-4bb0-a7cd-0b6ca3470979.png)

2023-03-27 05:07 UTC, iioo3356 approved these changes

2023-03-27 05:07 UTC, iioo3356 commented on src/front-end/timepay-admin/src/interfaces/ReportItem.ts
> +export interface Item {
변수 이름을 ReportItem으로 바꾸는 게 더 명확할 것 같습니다

2023-03-27 11:25 UTC, iioo3356 commented on src/front-end/timepay-admin/src/styles/constants/colors.ts
> +  SLIVERGRAY: '#CDCDCD',
가운데에 언더바 넣어주시면 더 읽기 편할 것 같습니다!

2023-03-27 14:15 UTC, iioo3356 requested changes

2023-03-27 14:29 UTC, JinLee25154 approved these changes
수고하셨습니다 :)

2023-03-27 17:05 UTC, seiyoon approved these changes
🤩👍

2023-03-28 04:53 UTC, suyunup commented on src/front-end/timepay-admin/src/components/ReportSearchForm/ReportSearchForm.styles.tsx
확인부탁드립니다~

2023-03-28 04:56 UTC, iioo3356 commented on src/front-end/timepay-admin/src/components/ReportSearchForm/ReportSearchForm.styles.tsx
확인했습니다! 감사합니당~~!!

2023-03-28 04:57 UTC, iioo3356 commented on src/front-end/timepay-admin/src/styles/constants/colors.ts
> +  SLIVERGRAY: '#CDCDCD',
감사합니당~

2023-03-28 04:57 UTC, iioo3356 approved these changes

2023-03-28 04:58 UTC, iioo3356 commented
고생하셨습니당~~!!! 😘

2023-03-28 09:16 UTC, merged