[관리자] 회원 관리 - 활동 목록, 정보 수정 모달 업데이트
kookmin-sw/capstone-2023-09 pull request #89
Opened 2023-04-12 04:40 UTC by JinLee25154

2023-04-12 14:49 UTC, iioo3356 requested changes
훨씬 읽기 좋은 코드인 것 같아요!! 더미 이미지를 링크로 변경하는 것만 부탁드립니당

2023-04-12 14:49 UTC, iioo3356 commented on src/front-end/timepay-admin/src/assets/images/timepayLogo.png
요 이미지 어드민 페이지에서 사용할 일 없을 것 같은데 삭제해주실 수 있을까요?

2023-04-12 14:49 UTC, iioo3356 commented on src/front-end/timepay-admin/src/pages/UserManagement/editModal.tsx
> +  const [editProfileImg, setEditProfileImg] = useState(sampleImg);
샘플 이미지를 그냥 웹에서 이미지 링크 따와서 하는 것도 좋을 것 같아요!

2023-04-18 05:05 UTC, JinLee25154 commented on src/front-end/timepay-admin/src/assets/images/timepayLogo.png
삭제했습니다!

2023-04-18 06:15 UTC, iioo3356 commented on src/front-end/timepay-admin/src/assets/images/timepayLogo.png
감사합니다~~

2023-04-18 06:17 UTC, iioo3356 approved these changes
고생하셨습니다! 😙

2023-04-18 06:19 UTC, merged